### ISSUE TITLE
Análisis de amplificación incompleto

### ISSUE THREAD

**Issue by edgardomarchi** [Ronapa/Circuitos2#11]
En la sección [Análisis de amplificación](https://github.com/Ronapa/Circuitos2#an%C3%A1lisis-de-la-amplificaci%C3%B3n) sólo se muestra una expresión sin valores para la primer etapa y un análisis para el realimentador, pero no se analiza la amplificación a lazo abierto por lo que no se puede analizar el efecto de la misma sobre la compensación y/o distorsión.

**Comment by segunmo** [comment]
Análisis de amplificación por etapas hecho.
