### ISSUE TITLE
Elección de tecnología de componentes faltante

### ISSUE THREAD

**Issue by edgardomarchi** [Ronapa/Circuitos2#12]
La sección [Tecnologías utilizadas](https://github.com/Ronapa/Circuitos2#elecci%C3%B3n-de-las-tecnolog%C3%ADas-utilizadas) solo menciona la tecnología de algunos componentes. Falta documentar la elección de la tecnología de resistencias capacitores, etc. etc. según etapa.

**Comment by segunmo** [comment]
Tecnologías utilizadas completado. Se agregó Resistores, Capacitores, LEDs, Diodos.
