### ISSUE TITLE
Análisis de compensación faltante

### ISSUE THREAD

**Issue by edgardomarchi** [Ronapa/Circuitos2#13]
En la sección [Compensación del circuito y respuesta en frecuencia](https://github.com/Ronapa/Circuitos2#compensaci%C3%B3n-del-circuito-y-respuesta-en-frecuencia) se muestra una simulación a lazo abierto, pero no se realiza ningún análisis sobre la misma, ni se indican los valores de MF y/o MG. Tampoco se habla de con que criterio se compensó el circuito.

**Comment by segunmo** [comment]
Gráficos de compensación hechos. Falta explicación.

**Comment by segunmo** [comment]
Explicación que apoya a los gráficos hecha.
