### ISSUE TITLE
Vaga determinación de potencia máxima 

### ISSUE THREAD

**Issue by edgardomarchi** [Ronapa/Circuitos2#14]
En la determinación de la potencia máxima, debe quedar claro que una limitación práctica es la disponibilidad de instrumental (fuentes) de laboratorio. Esto debería quedar claro en la sección [Potencia-en-la carga](https://github.com/Ronapa/Circuitos2#potencia-en-la-carga).

**Comment by segunmo** [comment]
Limitación explicada.
