### ISSUE TITLE
Potencia disipada en los transistores, peor caso

### ISSUE THREAD

**Issue by edgardomarchi** [Ronapa/Circuitos2#16]
La potencia disipada en los transistores, calculada en la sección [Potencia disipada en los transistores](https://github.com/Ronapa/Circuitos2#potencia-disipada-en-los-transistores) no refleja si fué evaluada en el peor caso de disipación (<img src="http://latex.codecogs.com/gif.latex?\frac{2.V_{cc}}{\pi}" border="0"/>)

**Comment by segunmo** [comment]
El resultado era el mismo que con la tensión máxima pero le corregí la fórmula.
