### ISSUE TITLE
Revisión de concepto

### ISSUE THREAD

**Issue by edgardomarchi** [Ronapa/Circuitos2#6]
En la sección [Diseño](https://github.com/Ronapa/Circuitos2/#dise%C3%B1o) se menciona que la eficiencia aumenta por tener dos transistores en paralelo, ya que siempre conduce uno sólo. Esta afirmación no es conceptualmente correcta ya que la eficiencia depende de varios otros factores. Revisar este concepto.

**Comment by segunmo** [comment]
Cambiado eficiencia por excursión. Teniendo dos transistores en serie se tiene una caída de Vce de dos transistores, en paralelo nos ahorramos esto.
