### ISSUE TITLE
Explicación de R39

### ISSUE THREAD

**Issue by edgardomarchi** [Ronapa/Circuitos2#7]
En la sección [Etapa de entrada](https://github.com/Ronapa/Circuitos2/#etapa-de-entrada) la explicación de R39 no es adecuada, ya que la especificación fija la amplificación por lo que la relación de compromiso para determinar este valor pasa por otro lado (por ejemplo, impedancia que presenta el nodo a las bases).

**Comment by segunmo** [comment]
Cambiado, el valor de R39 está explicado en la etapa de Análisis de amplificación.
