### ISSUE TITLE
Imágen faltante

### ISSUE THREAD

**Issue by edgardomarchi** [Ronapa/Circuitos2#8]
En el último párrafo de la sección [VAS y multiplicador de vbe](https://github.com/Ronapa/Circuitos2/#etapa-vas-y-multiplicador-de-vbe) se hace mención a la imagen siguiente, pero no existe ninguna imagen que se corresponda. Cabe recordar que el multiplicador de Vbe es parte de la etapa de salida.

**Comment by segunmo** [comment]
Imagen agregada.
